<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy" data-toc-modified-id="NumPy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy</a></span><ul class="toc-item"><li><span><a href="#Homework" data-toc-modified-id="Homework-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Homework</a></span></li></ul></li></ul></div>

# NumPy

NumPy è una libreria open source per il linguaggio di programmazione Python, che aggiunge supporto a grandi **matrici**
e **array multidimensionali** insieme a una vasta collezione di funzioni matematiche di alto livello per poter operare 
efficientemente su queste strutture dati.

##### Le basi: come creo un array?

**Ricorda** : NumPy considera come array sia le matrici che i vettori! 

*Array* : insieme organizzato di elementi omogenei, identificati da uno stesso nome e da uno o più indici.

In [1]:
#importo la libreria di riferimento

import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
squares = np.array([x**2 for x in range(10)])
squares

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
type(squares)

numpy.ndarray

###### Metodi utili per array

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int32'

In [8]:
a.itemsize

4

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

###### Creare array a partire da tipi diversi in Python

La funzione **range( )** ritorna una sequenza di numeri, partendo da 0 di default, e incrementa di 1 (di default), e si ferma prima di uno specifico numero.

In [11]:
squares = [x**2 for x in range(10)]         # list
cubes = tuple(x**3 for x in range(10))      # tuple
evens = {x for x in range(10) if x%2 == 0}  # set

print(type(squares))
print(type(cubes))
print(type(evens))

<class 'list'>
<class 'tuple'>
<class 'set'>


In [12]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [13]:
cubes

(0, 1, 8, 27, 64, 125, 216, 343, 512, 729)

In [14]:
evens

{0, 2, 4, 6, 8}

In [15]:
a = np.array(squares)
b = np.array(cubes)
c = np.array(evens)

if type(a) == type(b) == type(c):
    print(type(a))

<class 'numpy.ndarray'>


In [16]:
seq2 = [[x, x**2, x**3] for x in range(10)]
seq3 = [[[x for x in range(3)], [y for y in range(3, 6)]] for z in range(10)]

a = np.array(seq2) 
b = np.array(seq3)

print(a.ndim)
print(b.ndim)

2
3


In [17]:
zeros = np.zeros((3, 3), dtype=np.int32) 
ones = np.ones((2, 2), dtype=np.float64)
empty = np.empty((3, 3))

print(zeros, zeros.dtype.name)
print(ones, ones.dtype.name)
print(empty, empty.dtype.name)

[[0 0 0]
 [0 0 0]
 [0 0 0]] int32
[[1. 1.]
 [1. 1.]] float64
[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 7.233e-321]
 [0.000e+000 0.000e+000 0.000e+000]] float64


In [18]:
a = np.arange(5, 30, 5) 
a

array([ 5, 10, 15, 20, 25])

In [19]:
from numpy import pi

c = np.linspace(0, 2*pi, 10)

f = np.sin(c)
f

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [20]:
def f(row_num, col_num):
    return 2*row_num + col_num

F = np.fromfunction(f, (3, 3), dtype=int)
F

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

###### Stampare array

In [21]:
dim1 = np.arange(15)                  
dim2 = np.arange(15).reshape(3, 5)    
dim3 = np.arange(24).reshape(2, 3, 4)  
print(dim1)
print('\n')
print(dim2)
print('\n')
print(dim3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


###### Operazioni comuni con NumPy

In [22]:
a = np.arange(10) 
b = np.array([2 for x in range(10)])
c = np.ones(10, dtype=int)
result = a + b - c 

print(result)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
result < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [24]:
a = np.ones(15).reshape(3, 5)
b = np.ones(15).reshape(5, 3)

mult = a * 10           
dot_prod1 = a.dot(b)   
dot_prod2 = np.dot(a, b)

print(mult, end='\n\n')
print(dot_prod1, end='\n\n')
print(dot_prod2)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [25]:
a = np.ones(10, dtype=int)
b = np.ones(10, dtype=float)
c = np.ones(10, dtype=complex)

a_plus_b = a + b 
b_plus_c = b + c 

print(a_plus_b.dtype.name)
print(b_plus_c.dtype.name)


float64
complex128


In [26]:
a = np.arange(1, 11)
print('Sum:', a.sum())
print('Min:', a.min())
print('Max:', a.max())

Sum: 55
Min: 1
Max: 10


In [27]:
a = np.arange(15).reshape(3, 5) + 1

print(a.sum(axis=0)) 
print(a.min(axis=1)) 
a

[18 21 24 27 30]
[ 1  6 11]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

###### Funzioni di diversa utilità

In [28]:
a = np.linspace(0, 2*pi, 10000)

sin_a = np.sin(a)
sqrt_a = np.sqrt(a)
exp_a = np.exp(a)

print(sin_a, end='\n\n')
print(sqrt_a, end='\n\n')
print(exp_a, end='\n\n')

[ 0.00000000e+00  6.28381328e-04  1.25676241e-03 ... -1.25676241e-03
 -6.28381328e-04 -2.44929360e-16]

[0.         0.02506754 0.03545085 ... 2.50637757 2.50650293 2.50662827]

[  1.           1.00062858   1.00125755 ... 534.81909228 535.15526825
 535.49165552]



##### Generazione numeri casuali

Per la generazione di array di numeri causali a partire da vari tipi di distribuzione statistica si utilizza il modulo *random*:

riferimento: https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html.

In [29]:
import numpy.random as rdm

In [30]:
A = rdm.random((4,4))
A

array([[0.01890649, 0.33494389, 0.67640373, 0.41538939],
       [0.94475276, 0.82569022, 0.5725889 , 0.89080955],
       [0.00717492, 0.66429142, 0.06741774, 0.06169575],
       [0.32363034, 0.89380421, 0.83570583, 0.98578978]])

In [31]:
I = rdm.randint(1,7,(4,4))
I

array([[5, 2, 6, 6],
       [2, 6, 4, 2],
       [4, 1, 4, 2],
       [5, 4, 3, 5]])

In [32]:
N = rdm.normal(2,1,(4,6))
N

array([[3.03795704, 1.73913698, 2.74911965, 3.89629523, 3.32585421,
        1.34408901],
       [2.85834591, 1.13386189, 3.64416993, 2.11827528, 1.67713518,
        1.95301575],
       [1.82682344, 2.5559141 , 2.97316674, 2.57961695, 1.35201785,
        2.39855445],
       [1.99662211, 0.9248329 , 1.16338433, 2.34970733, 1.4211395 ,
        0.96833117]])

###### Indexing, slicing, and iterating

In [33]:
A = np.array([x**2 for x in range(1, 11)]).reshape(2, 5)

print(A, end='\n\n')
print('A[0]\t\t', A[0])
print('A[-1]\t\t', A[-1])
print('A[0][0]\t\t', A[0][0])
print('A[-1][-1]\t', A[-1][-1])


[[  1   4   9  16  25]
 [ 36  49  64  81 100]]

A[0]		 [ 1  4  9 16 25]
A[-1]		 [ 36  49  64  81 100]
A[0][0]		 1
A[-1][-1]	 100


In [34]:
cubes = np.arange(1, 13).reshape(4, 3)**3

print(cubes[:,:], end='\n\n')         
print('First Column:\t', cubes[:, 0]) 
print('Last Column:\t', cubes[:, -1]) 
print('First Row:\t', cubes[0, :])    
print('Last Row:\t', cubes[-1, :])

[[   1    8   27]
 [  64  125  216]
 [ 343  512  729]
 [1000 1331 1728]]

First Column:	 [   1   64  343 1000]
Last Column:	 [  27  216  729 1728]
First Row:	 [ 1  8 27]
Last Row:	 [1000 1331 1728]


In [35]:
A = np.array([x+1 for x in range(10)])
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
for a in A:
    print(a, end=',')

1,2,3,4,5,6,7,8,9,10,

In [37]:
A = A.reshape(2, 5)

for a in A[0,:]: 
    print(a**2, end=',')

1,4,9,16,25,

###### Come splittare gli arrays

In [38]:
a = np.ones(9).reshape(3, 3)

a_1, a_2, a_3 = np.hsplit(a, 3)

print(a, end='\n\n')
print(a_1, end='\n\n')
print(a_2, end='\n\n')
print(a_3, end='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]



## Homework

- Crea una matrice 3x3 con valori compresi tra 0 e 8
- Crea un vettore random con 30 elementi e trova il valore medio
- Trova gli indici degli elementi diversi da zero del seguente array [3,5,0,4,0,8,0]
- Scrivi un programma per ottenere gli indici degli elementi ordinati di un dato array
    ,esempio : 
     - array: [1023 5202 6230 1671 1682 5241 4532]
     - indice degli elementi ordinati dell'array :[0 3 4 6 1 5 2]
- Scrivi un programma che calcola la media attraverso la dimensione, in un array 2D
    ,esempio : 
     - array:   
       [[10 30]
       
       [20 60]]
     - media di ogni colonna: [15 45]
     - media di ogni riga: [20 40]

Inoltre se volete continuare ad esercitarvi trovate una vasta gamma di esercizi di ogni tipologia su questo sito:
https://www.w3resource.com/python-exercises/numpy/index.php
    

In [17]:
#esercizio 1
import numpy as np
l= np.arange(9).reshape(3, 3)
l


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
#esercizio 2
import numpy.random as rdm

vettore= rdm.rand(30)
print ('la media è:\t',vettore.sum()/len(vettore))
vettore

la media è:	 0.4635933303613248


array([0.88545118, 0.03814526, 0.33614577, 0.08035147, 0.56257604,
       0.45180528, 0.94490468, 0.73971754, 0.69299017, 0.62192778,
       0.32420705, 0.61672176, 0.99496855, 0.5447662 , 0.90622872,
       0.41043084, 0.16189469, 0.47783975, 0.34420162, 0.4775362 ,
       0.29239339, 0.24093299, 0.27260572, 0.31017928, 0.40589846,
       0.35692554, 0.43095831, 0.25833155, 0.29542127, 0.43134285])

In [24]:
np.mean(vettore)

0.4635933303613248

In [27]:
esempio= np.random.rand(30)
esem

array([0.38575741, 0.42988268, 0.48948445, 0.86187021, 0.88479431,
       0.30609077, 0.6714646 , 0.78655002, 0.3946493 , 0.654321  ,
       0.40940196, 0.57751825, 0.92057887, 0.61542283, 0.40589373,
       0.59265409, 0.43546728, 0.57594039, 0.42715318, 0.38822052,
       0.91080467, 0.30368368, 0.88245169, 0.0689371 , 0.94874816,
       0.84090088, 0.12412374, 0.20391157, 0.2904362 , 0.57885729])

In [2]:
#esercizio 3
import numpy as np
arr= np.array([3,5,0,4,0,8,0])
result = np.where(arr)
result

(array([0, 1, 3, 5], dtype=int64),)

In [12]:
#esercizio 4
g = np.array([1234,5654,1800,4634,8100])
h= sorted(g)
print ('array disordinato:\t',g)
print ('array ordinato:\t',h)
print('\n')
risultato = np.where(g)
risultato_ord= np.where(h)
print ('indice degli elementi disordinato dell_array:\t',risultato)
print ('indice degli elementi ordinati dell_array:\t',risultato)

array disordinato:	 [1234 5654 1800 4634 8100]
array ordinato:	 [1234, 1800, 4634, 5654, 8100]


indice degli elementi disordinato dell_array:	 (array([0, 1, 2, 3, 4], dtype=int64),)
indice degli elementi ordinati dell_array:	 (array([0, 1, 2, 3, 4], dtype=int64),)


In [7]:
#esercizio 5
import numpy as np
k = np.array([89,57,35,75]).reshape(2,2)
print('array:\t\n',k)
print('\n')
print('media di ogni colonna:\t',k.mean(axis=0))
print('media di ogni riga:\t',k.mean(axis=1))

array:	
 [[89 57]
 [35 75]]


media di ogni colonna:	 [62. 66.]
media di ogni riga:	 [73. 55.]


In [13]:
g = np.array([1234,5654,1800,4634,8100])
print (np.argsort(g))

[0 2 3 1 4]


In [52]:
import numpy as np
c= np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
type(c)

numpy.ndarray

In [54]:
c.shape

(3, 3)

In [61]:
c.reshape(3,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [65]:
array_da_12= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_da_12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
array_da_12.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [67]:
array_da_12.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [70]:
array_da_12.shape=(2,6)
array_da_12

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [71]:
array_da_12.shape

(2, 6)

In [72]:
array_da_12.dtype

dtype('int32')

In [74]:
a= np.array([100,25,70,55])
b= np.array([45,12,5,-21])
a+b

array([145,  37,  75,  34])

In [75]:
b>0

array([ True,  True,  True, False])

In [76]:
b<0

array([False, False, False,  True])

In [77]:
a*0.8

array([80., 20., 56., 44.])

In [79]:
(a*0.8).dtype

dtype('float64')

In [80]:
b.dtype

dtype('int32')

In [87]:
v=np.arange(1,49)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [88]:
v.shape

(48,)

In [93]:
v12x4=v.reshape(12,4)
v12x4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36],
       [37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [95]:
v6x8= np.arange(1,49).reshape(6,8)
v6x8

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [104]:
np.random.random((3,3))*100

array([[ 1.63547615, 76.39158998, 22.00272101],
       [95.06214888, 53.97201557, 26.74573115],
       [47.72307589, 54.51450516, 63.53931997]])

In [106]:
vuoto = np.empty((5,5))
vuoto

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.95819673e-306, 6.23054972e-307],
       [8.45593934e-307, 7.56593017e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306],
       [7.56597770e-307, 6.23059726e-307, 8.90104239e-307,
        6.89804133e-307, 1.69118923e-306],
       [1.24611945e-306, 6.23059726e-307, 1.42420209e-306,
        9.34605037e-307, 1.05700515e-307],
       [1.11261774e-306, 1.29060871e-306, 8.34424766e-308,
        2.12203497e-312, 2.10081501e-312]])

In [109]:
uno=np.ones((5,5))
uno

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [111]:
zero=np.zeros((4,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [113]:
seven = np.full((6,5),7)
seven

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [115]:
piu_dimensioni= np.full((3,4,5),7)
piu_dimensioni

array([[[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]]])

In [116]:
valori= np.array([1,2,3,4,5,6,7,8,9])
valori

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
valori[6]

7

In [122]:
valori[3:8]

array([4, 5, 6, 7, 8])

In [123]:
valori[:5]

array([1, 2, 3, 4, 5])

In [126]:
valori[5:]

array([6, 7, 8, 9])

In [127]:
valori[-3:]

array([7, 8, 9])

In [139]:
duedimensioni=np.array(np.random.random(28)*10).reshape(7,4)
duedimensioni

array([[0.64660118, 3.70078515, 8.1352845 , 4.4290186 ],
       [7.3247489 , 3.12727883, 3.11092801, 1.94155013],
       [1.84724376, 8.92454906, 3.02105354, 8.08528755],
       [4.00467282, 5.51895848, 6.52449911, 8.43983898],
       [1.67002289, 5.72783429, 9.25330788, 5.77044065],
       [0.87087911, 2.25650337, 8.64699864, 4.03275442],
       [6.81217411, 0.78536647, 8.77711923, 3.03120973]])

In [142]:
duedimensioni[0][0]

0.6466011789932491

In [143]:
type(duedimensioni[1])

numpy.ndarray

In [144]:
duedimensioni[3:6]

array([[4.00467282, 5.51895848, 6.52449911, 8.43983898],
       [1.67002289, 5.72783429, 9.25330788, 5.77044065],
       [0.87087911, 2.25650337, 8.64699864, 4.03275442]])

In [147]:
duedimensioni[3:6][1]

array([1.67002289, 5.72783429, 9.25330788, 5.77044065])

In [148]:
duedimensioni[3:6][1][1]

5.727834293861001

In [153]:
#modifica valori in matrice
duedimensioni[2][2]=888
duedimensioni

array([[6.46601179e-01, 3.70078515e+00, 8.13528450e+00, 4.42901860e+00],
       [7.32474890e+00, 3.12727883e+00, 3.11092801e+00, 1.94155013e+00],
       [1.84724376e+00, 8.92454906e+00, 8.88000000e+02, 8.08528755e+00],
       [4.00467282e+00, 5.51895848e+00, 6.52449911e+00, 8.43983898e+00],
       [1.67002289e+00, 5.72783429e+00, 9.25330788e+00, 5.77044065e+00],
       [8.70879113e-01, 2.25650337e+00, 8.64699864e+00, 4.03275442e+00],
       [6.81217411e+00, 7.85366472e-01, 8.77711923e+00, 3.03120973e+00]])

In [178]:
t = np.array([12,45,-35,65,-678,48,27])
t[t<0]

array([ -35, -678])

In [185]:
tavola= np.array([4,3,1,2,5,2,7,3,1,6,8,4,5,8,6,7]).reshape(4,4)
tavola

array([[4, 3, 1, 2],
       [5, 2, 7, 3],
       [1, 6, 8, 4],
       [5, 8, 6, 7]])

In [ ]:
import numpy as np
import sys
import re
from random import shuffle
ELEMENTI_LATO = 4

def genera_gioco():
    elementi=list(range(1,int(ELEMENTI_LATO**2/2)+1))*2
    shuffle(elementi)
    matrice_controllo = np.zeros((ELEMENTI_LATO, ELEMENTI_LATO), dtype=np.int)
    
    return np.array(elementi).reshape(ELEMENTI_LATO,ELEMENTI_LATO),matrice_controllo

def stampa_matrice(da_stampare):
    for x in da_stampare:
        print ('   '.join(np.where(x==0, 'X', x.astype(int))))
        print()
        
def gioco_finito():
    return trovati[trovati == 0].size==0

def soluzione():
    da_stampare=tavola*np.ones((ELEMENTI_LATO, ELEMENTI_LATO))
    stampa_matrice(da_stampare)
    
def uscire(comm):
    if comm.strip().lower()=='fine':
        soluzione()
        print("Partita interrotta!")
        sys.exit()
        
def nuova_mano():
    punto1= input("Punto 1")
    uscire(punto1)
    punto2= input("punto 2 ")
    uscire(punto2)
    if re.match(r'^\d\s+\d$',punto1)!=None and re.match(r'^\d\s+\d$', punto2)!=None:
        x1, y1=punto1.split()
        x2, y2=punto2.split()
        verifica(int(x1),int(y1),int(x2),int(y2))
        
def verifica(x1,y1,x2,y2):
    if tavola[x1][y1]==tavola[x2][y2]:
        trovati[x1][y1]=1
        trovati[x2][y2]=1
        print(f"BRAVO !! Hai trovato la coppia di {tavola[x1][y1]}")
    else:
        print(f"Purtroppo hai sbagliato. C'erano {tavola[x1][y1]} e {tavola[x2][y2]}")
        
def gioco():
    while not gioco_finito():
        nuova_mano()
        stampa_matrice(tavola*trovati)
    print("Complimenti . . . hai vinto!!!")
    
tavola,trovati = genera_gioco()
gioco()
        



Punto 11
punto 2 2
X   X   X   X

X   X   X   X

X   X   X   X

X   X   X   X

Punto 15
punto 2 4
X   X   X   X

X   X   X   X

X   X   X   X

X   X   X   X

Punto 12
punto 2 8
X   X   X   X

X   X   X   X

X   X   X   X

X   X   X   X

Punto 1k
punto 2 ho
X   X   X   X

X   X   X   X

X   X   X   X

X   X   X   X

Punto 1[0][2]
punto 2 [1][2]
X   X   X   X

X   X   X   X

X   X   X   X

X   X   X   X

Punto 1x
punto 2 x
X   X   X   X

X   X   X   X

X   X   X   X

X   X   X   X

Punto 1X
punto 2 X
X   X   X   X

X   X   X   X

X   X   X   X

X   X   X   X

